import { IDashboardInspectionListItem, IPropertyInspectionFormData } from '@/types'
import { Property } from '@/components/reusable/PropertyCard/PropertyCard'

export const MOCK_PROPERTY_DETAILS: Property = {
  title: '2024 Annual Roof Inspection',
  property: 'Sunset Office Complex (Demo Property)',
  propertyName: 'Sunset Office Complex',
  id: 'INS2323',
  type: 'Commercial',
  updated_at: '12 Jan, 2025',
  address: '1234 Sunset Blvd, Los Angeles, USA',
  nextInspection: 'Jan 12, 2025',
  date: 'May 15, 2025',
  score: 76,
}

export const DEMO_FROM_CONFIG: IPropertyInspectionFormData = {
  dashboardId: 'cmne1xe9p0001s4u8ua22cmm9',
  criteriaId: 'cmmlnbk3l00040ou8pe4da8id',
  form: {
    headerFields: [
      {
        key: 'inspectionTitle',
        type: 'text',
        label: 'Inspection Title',
        order: 1,
        // options: null,
        isSystem: true,
        required: true,
        placeholder: 'Enter inspection title',
      },
      {
        key: 'propertyType',
        type: 'dropdown',
        label: 'Property Type',
        order: 2,
        options: ['Commercial', 'Residential'],
        isSystem: true,
        required: false,
        placeholder: 'Select property type',
      },
      {
        key: 'roofSystemType',
        type: 'dropdown',
        label: 'Roof System Type',
        order: 3,
        options: ['TPO', 'Metal', 'Shingle'],
        isSystem: true,
        required: false,
        placeholder: 'Select roof system',
      },
      {
        key: 'drainageType',
        type: 'dropdown',
        label: 'Drainage Type',
        order: 4,
        options: ['Internal', 'External'],
        isSystem: true,
        required: false,
        placeholder: 'Select drainage type',
      },
    ],
    scoringCategories: [
      {
        key: 'surfaceCondition',
        label: 'Surface Condition',
        order: 1,
        isSystem: true,
        maxPoints: 25,
      },
      {
        key: 'seamsFlashings',
        label: 'Seams & Flashings',
        order: 2,
        isSystem: true,
        maxPoints: 20,
      },
      {
        key: 'drainagePonding',
        label: 'Drainage & Ponding',
        order: 3,
        isSystem: true,
        maxPoints: 15,
      },
      {
        key: 'penetrations',
        label: 'Penetrations & Accessories',
        order: 4,
        isSystem: true,
        maxPoints: 10,
      },
      {
        key: 'repairsHistory',
        label: 'Repairs & Patch History',
        order: 5,
        isSystem: true,
        maxPoints: 10,
      },
      {
        key: 'ageExpectedLife',
        label: 'Age vs. Expected Life',
        order: 6,
        isSystem: true,
        maxPoints: 10,
      },
    ],
    mediaFields: [
      {
        key: 'mediaFiles',
        type: 'file',
        label: 'Media  Files',
        order: 1,
        accept: ['image/*', 'video/*'],
        isSystem: true,
        placeholder: 'Upload a media file',
      },
      {
        key: 'aerialMap',
        type: 'file',
        label: 'Aerial Map!!',
        order: 2,
        accept: ['image/*', 'video/*'],
        isSystem: true,
        placeholder: 'Upload your file.!!',
      },
      {
        key: 'tour3d',
        type: 'embed',
        label: '3D Tours',
        order: 3,
        // accept: null,
        isSystem: true,
        placeholder: 'Paste Source URL / iframe Code',
      },
      {
        key: 'documents',
        type: 'document',
        label: 'Documents',
        order: 4,
        // accept: null,
        isSystem: true,
        placeholder: 'Add Documents',
      },
    ],
    repairPlanningConfig: {
      statuses: ['Urgent', 'Maintenance', 'Replacement Planning'],
    },
    nteConfig: {
      label: 'NTE (Not-To-Exceed)',
      placeholder: 'Enter NTE value',
    },
    additionalNotesConfig: {
      label: 'Additional Notes/Comments',
      placeholder: 'Type Any Additional Notes/Comments',
    },
    healthThresholdConfig: {
      fair: {
        maxScore: 70,
        minScore: 21,
        remainingLifeMaxYears: 5,
        remainingLifeMinYears: 3,
      },
      good: {
        maxScore: 20,
        minScore: 0,
        remainingLifeMaxYears: 2,
        remainingLifeMinYears: 1,
      },
      poor: {
        maxScore: 100,
        minScore: 71,
        remainingLifeMaxYears: 2,
        remainingLifeMinYears: 0,
      },
    },
  },
}

export const DEMO_INSPECTIN_DATA: IDashboardInspectionListItem = {
  id: 'cmnwklhso0003ygu8jre9wxk2',
  dashboardId: 'cmne1xe9p0001s4u8ua22cmm9',
  inspectorId: 'cmmlnbk3900030ou81inxlhw6',
  headerData: {
    inspectionTitle: '',
    drainageType: '',
    propertyType: '',
    roofSystemType: '',
  },
  scores: {
    penetrations: {
      notes: '',
      score: 0,
    },
    repairsHistory: {
      notes: '',
      score: 0,
    },
    seamsFlashings: {
      notes: '',
      score: 0,
    },
    ageExpectedLife: {
      notes: '',
      score: 0,
    },
    drainagePonding: {
      notes: '',
      score: 6,
    },
    surfaceCondition: {
      notes: '',
      score: 6,
    },
  },
  overallScore: 12,
  healthLabel: 'Poor',
  remainingLife: '0-2 Years',
  repairItems: [
    {
      id: 'repair_1776047116608_2',
      title: 'Leaking bathroom pipe',
      status: 'Urgent',
      description: 'Water leaking under the sink in apartment 3B, needs immediate fixing.',
    },
    {
      id: 'repair_1776047116608_3',
      title: 'Air conditioner not cooling',
      status: 'Maintenance',
      description: 'Tenant reported AC is running but not cooling properly in unit 5A.',
    },
    {
      id: 'repair_1776047116608_4',
      title: 'Broken lobby light',
      status: 'Replacement Planning',
      description: 'Main lobby ceiling light is flickering and sometimes turns off.',
    },
  ],
  nteValue: 70,
  additionalComments: 'Sed est delectus po',
  inspectedAt: '2026-04-13T02:25:15.310Z',
  createdAt: '2026-04-13T02:25:16.632Z',
  updatedAt: '2026-04-13T02:25:16.632Z',
  mediaFiles: [
    {
      id: 'cmnwklhtd0004ygu8ffzp18w3',
      inspectionId: 'cmnwklhso0003ygu8jre9wxk2',
      fileName:
        'YTDown.com_YouTube_Exercises-and-Stretches-for-Arm-Pain_Media_CZ9rvwtaK4Q_004_360p.mp4',
      fileType: 'VIDEO',
      url: 'https://leaving-database-clinical-used.trycloudflare.com/public/storage/inspections/cmnwklhso0003ygu8jre9wxk2/1776047116653_ytdown.com_youtube_exercises-and-stretches-for-arm-pain_media_cz9rvwtak4q_004_360p.mp4',
      size: 4245759,
      mediaFieldKey: 'mediaFiles',
      // category: null,
      uploadedAt: '2026-04-13T02:25:16.656Z',
    },
    {
      id: 'cmnwklhtp0005ygu8bi1t5to1',
      inspectionId: 'cmnwklhso0003ygu8jre9wxk2',
      fileName: 'sample-5s.mp4',
      fileType: 'VIDEO',
      url: 'https://leaving-database-clinical-used.trycloudflare.com/public/storage/inspections/cmnwklhso0003ygu8jre9wxk2/1776047116665_sample-5s.mp4',
      size: 2848208,
      mediaFieldKey: 'mediaFiles',
      // category: null,
      uploadedAt: '2026-04-13T02:25:16.668Z',
    },
    {
      id: 'cmnwklhtr0006ygu8g4l7rynd',
      inspectionId: 'cmnwklhso0003ygu8jre9wxk2',
      fileName: 'cute-curious-gray-and-white-kitten-in-a-long-shot-photo.jpg',
      fileType: 'PHOTO',
      url: 'https://leaving-database-clinical-used.trycloudflare.com/public/storage/inspections/cmnwklhso0003ygu8jre9wxk2/1776047116670_cute-curious-gray-and-white-kitten-in-a-long-shot-photo.jpg',
      size: 16352,
      mediaFieldKey: 'mediaFiles',
      // category: null,
      uploadedAt: '2026-04-13T02:25:16.671Z',
    },
    {
      id: 'cmnwklhtt0007ygu8sbzh51ew',
      inspectionId: 'cmnwklhso0003ygu8jre9wxk2',
      fileName: 'cute-curious-gray-and-white-kitten-in-a-long-shot-photo.jpg',
      fileType: 'PHOTO',
      url: 'https://leaving-database-clinical-used.trycloudflare.com/public/storage/inspections/cmnwklhso0003ygu8jre9wxk2/1776047116672_cute-curious-gray-and-white-kitten-in-a-long-shot-photo.jpg',
      size: 16352,
      mediaFieldKey: 'mediaFiles',
      // category: null,
      uploadedAt: '2026-04-13T02:25:16.672Z',
    },
    {
      id: 'cmnwklhtv0008ygu8pr38tsx6',
      inspectionId: 'cmnwklhso0003ygu8jre9wxk2',
      fileName: 'cute-curious-gray-and-white-kitten-in-a-long-shot-photo.jpg',
      fileType: 'PHOTO',
      url: 'https://leaving-database-clinical-used.trycloudflare.com/public/storage/inspections/cmnwklhso0003ygu8jre9wxk2/1776047116673_cute-curious-gray-and-white-kitten-in-a-long-shot-photo.jpg',
      size: 16352,
      mediaFieldKey: 'mediaFiles',
      // category: null,
      uploadedAt: '2026-04-13T02:25:16.674Z',
    },
    {
      id: 'cmnwklhtw0009ygu8qsyvviuy',
      inspectionId: 'cmnwklhso0003ygu8jre9wxk2',
      fileName: 'cute-curious-gray-and-white-kitten-in-a-long-shot-photo.jpg',
      fileType: 'PHOTO',
      url: 'https://leaving-database-clinical-used.trycloudflare.com/public/storage/inspections/cmnwklhso0003ygu8jre9wxk2/1776047116675_cute-curious-gray-and-white-kitten-in-a-long-shot-photo.jpg',
      size: 16352,
      mediaFieldKey: 'mediaFiles',
      // category: null,
      uploadedAt: '2026-04-13T02:25:16.676Z',
    },
    {
      id: 'cmnwklhty000aygu8aeruq8w8',
      inspectionId: 'cmnwklhso0003ygu8jre9wxk2',
      fileName: 'encondos.pdf',
      fileType: 'PDF',
      url: 'https://leaving-database-clinical-used.trycloudflare.com/public/storage/inspections/cmnwklhso0003ygu8jre9wxk2/1776047116677_encondos.pdf',
      size: 1002705,
      mediaFieldKey: 'documents',
      // category: null,
      uploadedAt: '2026-04-13T02:25:16.678Z',
    },
    {
      id: 'cmnwklhu0000bygu8mwa6mrgv',
      inspectionId: 'cmnwklhso0003ygu8jre9wxk2',
      fileName: 'visitors.pdf',
      fileType: 'PDF',
      url: 'https://leaving-database-clinical-used.trycloudflare.com/public/storage/inspections/cmnwklhso0003ygu8jre9wxk2/1776047116679_visitors.pdf',
      size: 205536,
      mediaFieldKey: 'documents',
      // category: null,
      uploadedAt: '2026-04-13T02:25:16.680Z',
    },
  ],
}
