import { TooltipProvider } from '@/components/ui/tooltip'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { TwScreenSize } from '@/components/reusable/TwScreenSize'

const poppinsSans = Poppins({
  variable: '--font-poppins-sans',
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'strabra1979',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppinsSans.variable} antialiased`}>
        <TooltipProvider>{children}</TooltipProvider>
        <TwScreenSize />
      </body>
    </html>
  )
}
